# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: local
    hooks:
      - id: spell check
        name: Spell check files
        language: r
        entry: Rscript scripts/spell-check.R
        additional_dependencies:
          - spelling

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff for linting and formatting python
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
        # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/lorenzwalthert/precommit
    rev: 0.3.2
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: lintr
      - id: parsable-R
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: end-of-file-fixer
        exclude: '\.Rd'
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files
