[files]
extend-exclude = [
  "references/*.tsv",
  "references/*.json",
  "references/scripts/create-formatting-reference.py"
]

[default.extend-identifiers]
limitBAMsortRAM="limitBAMsortRAM"
outBAMsortingThreadN="outBAMsortingThreadN"
2023_TRU="2023_TRU"
