---
params:
  integration_group: "example_group"
  integrated_sce: NULL
  #method: !r as.vector(c("fastMNN", "harmony"))
  batch_column: "batch"

title: "`r glue::glue('Integration report for {params$integration_group}')`"
author: "CCDL"
date: "`r params$date`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, message = FALSE, echo = FALSE}
# knitr options
knitr::opts_chunk$set(
  echo = FALSE
)

library(SingleCellExperiment)
library(ggplot2)

# Set default ggplot theme
theme_set(theme_bw() + 
          theme(plot.margin = margin(rep(20, 4))))
```

```{r}
# check that input files are provided 
if(is.null(params$integrated_sce)){
  stop("Must provide a path to a RDS file containing a integrated SCE object.")
}

# define batch column 
batch_column <- params$batch_column
```


```{r}
# read in merged object
integrated_sce <- readr::read_rds(params$integrated_sce)

# get list of methods and UMAPs to grab for plotting later
methods <- c("fastMNN", "harmony")
umap_plot_names <- c("UMAP", glue::glue("{methods}_UMAP"))
```

UMAP showing batches before and after integration.

```{r}
# randomly shuffle cells prior to plotting
col_order <- sample(ncol(integrated_sce))
shuffled_sce <- integrated_sce[,col_order]

# set plot colors 
num_colors <- length(unique(integrated_sce[[batch_column]]))
plot_colors <- rainbow(n = num_colors)

# list of batch umaps for all pre/post integration
batch_umaps <- purrr::map(umap_plot_names, \(name){
  scater::plotReducedDim(shuffled_sce,
                         dimred = name,
                         colour_by = batch_column,
                         point_size = 0.1,
                         point_alpha = 0.4) +
    scale_color_manual(values = plot_colors, 
                       name = batch_column) +
    # relabel legend and resize dots
    guides(color = guide_legend(override.aes = list(size = 3),
                                label.theme = element_text(size = 10))) 
})

patchwork::wrap_plots(batch_umaps, ncol = 2,
                      guides = "collect")
```

# Session Info
<details>
<summary>R session information</summary>
```{r session_info}
if (requireNamespace("sessioninfo", quietly = TRUE)) {
  sessioninfo::session_info()
} else {
  sessionInfo()
}
```
</details>

