name: Check nextflow config

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  nf-config-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check nextflow params
        uses: docker://nextflow/nextflow:21.10.6
        with:
          args: nextflow config
