name: Check nextflow config

on:
  pull_request:
    branches:
      - main
      - development
      - scpca-prod-account
jobs:
  nf-config-check:
    runs-on: ubuntu-22.04
    container: nfcore/tools:3.2.0
    steps:
      - uses: actions/checkout@v4
      - name: Check nextflow params
        run: nextflow config
      - name: Check nextflow_schema file
        run: nf-core pipelines schema lint
